using Flowdock.Client.Context;
using Flowdock.Client.Domain;
using Flowdock.ViewModels;
using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
using MoqaLate.Autogenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Flowdock.VSUnitTests.ViewModels {
    public class MockFlowdockContext : FlowdockContext {

        public override Task<Flow> GetFlow(string flowId) {
            return Task.FromResult<Flow>(new Flow() {
                Id = "my flow",
                Users = ExpectedUsers
            });
        }

        public override Task<IEnumerable<Message>> GetMessagesForFlow(string id) {
            return Task.FromResult<IEnumerable<Message>>(ExpectedMessages);
        }
        
        public IEnumerable<Message> ExpectedMessages { get; set; }
        public List<User> ExpectedUsers { get; set; }
    }

    [TestClass]
    public class FlowViewModelTest {
        private static List<Message> _expectedMessages;
        private static List<User> _expectedUsers;

        private static MockFlowdockContext _mockFlowdockContext;
        private FlowViewModel _flowViewModel;

        [ClassInitialize]
        public static void BeforeAll(TestContext testContext) {
            _expectedMessages = new List<Message> {
                new Message() { User = 1, Event = "message", Content = "first message" },
                new Message() { User = 2, Event = "message", Content = "second message" }
            };

            _expectedUsers = new List<User> {
                new User() { Id = 1, Avatar = new Uri("http://www.fake.com/1.png") },
                new User() { Id = 2, Avatar = new Uri("http://www.fake.com/2.png") }
            };

            _mockFlowdockContext = new MockFlowdockContext();
            _mockFlowdockContext.ExpectedMessages = _expectedMessages;
            _mockFlowdockContext.ExpectedUsers = _expectedUsers;
        }

        [TestInitialize]
        public void BeforeEach() {
            _flowViewModel = new FlowViewModel(new AppSettingsMoqaLate(), _mockFlowdockContext, new ProgressServiceMoqaLate(), new NavigationManagerMoqaLate(), new FlowStreamingConnectionMoqaLate());
        }
        
        [TestMethod]
        public void ShouldLoadFlowMessages() {
            _flowViewModel.Activate();

            Assert.AreEqual(_expectedMessages.Count, _flowViewModel.Messages.Count);
        }

        [TestMethod]
        public void ShouldGetCorrectAvatarForMessage() {
            _flowViewModel.Activate();

            Assert.AreEqual(_expectedUsers.Count, _flowViewModel.Messages.Count);

            // Then, make sure that the avatar maches to the the message the user made
            for (var i = 0; i < _expectedUsers.Count; i++) {
                Assert.AreEqual(_expectedUsers[i].Avatar, _flowViewModel.Messages[i].Avatar);
            }
        }
    }
}