using Flowdock.ViewModels;
using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
using MoqaLate.Autogenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Flowdock.VSUnitTests.ViewModels {

	[TestClass]
	public class LoginCommandTest {
		private FlowdockContextMoqaLate _flowdockContext;
		private LoginViewModel _loginViewModel;
		private LoginCommand _command;

		[TestInitialize]
		public void BeforeEach() {
			_flowdockContext = new FlowdockContextMoqaLate();
			_loginViewModel = new LoginViewModel(_flowdockContext, new AppSettingsMoqaLate(), new NavigationManagerMoqaLate());
			_command = new LoginCommand(_loginViewModel, _flowdockContext);
		}

		[TestMethod]
		public void CanExecute_false_if_username_and_password_are_null() {
			_loginViewModel.Username = null;
			_loginViewModel.Password = null;

			Assert.IsFalse(_command.CanExecute(null));
		}

		[TestMethod]
		public void CanExecute_false_if_username_and_password_are_blank() {
			_loginViewModel.Username = "";
			_loginViewModel.Password = "";

			Assert.IsFalse(_command.CanExecute(null));
		}

		[TestMethod]
		public void CanExecute_false_if_username_and_password_are_whitespace() {
			_loginViewModel.Username = "   ";
			_loginViewModel.Password = "      ";

			Assert.IsFalse(_command.CanExecute(null));
		}

		[TestMethod]
		public void CanExecute_true_if_username_and_password_are_set() {
			_loginViewModel.Username = "hello@kitty.com";
			_loginViewModel.Password = "somepassword";

			Assert.IsTrue(_command.CanExecute(null));
		}

		[TestMethod]
		public void Execute_does_not_execute_if_cant() {
			_loginViewModel.Username = "";
			_loginViewModel.Password = "";

			_command.Execute(null);
			Assert.AreEqual(0, _flowdockContext.LoginTimesCalled());
		}

		[TestMethod]
		public void Execute_does_execute_if_it_can() {
			_loginViewModel.Username = "someuser";
			_loginViewModel.Password = "somepassword";

			_command.Execute(null);
			Assert.AreEqual(1, _flowdockContext.LoginTimesCalled());
		}
	}
}
