using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Flowdock.Navigation;
namespace MoqaLate.Autogenerated
{
public partial class NavigationManagerMoqaLate : INavigationManager
{


// -------------- GoToLobby ------------


        private int _goToLobbyNumberOfTimesCalled;        

        

        public virtual bool GoToLobbyWasCalled()
{
   return _goToLobbyNumberOfTimesCalled > 0;
}


public virtual bool GoToLobbyWasCalled(int times)
{
   return _goToLobbyNumberOfTimesCalled == times;
}


public virtual int GoToLobbyTimesCalled()
{
   return _goToLobbyNumberOfTimesCalled;
}




        public void GoToLobby()
        {
            _goToLobbyNumberOfTimesCalled++;            

            
        }


// -------------- GoToFlow ------------


        private int _goToFlowNumberOfTimesCalled;        

        public string GoToFlowParameter_id_LastCalledWith;

        public virtual bool GoToFlowWasCalled()
{
   return _goToFlowNumberOfTimesCalled > 0;
}


public virtual bool GoToFlowWasCalled(int times)
{
   return _goToFlowNumberOfTimesCalled == times;
}


public virtual int GoToFlowTimesCalled()
{
   return _goToFlowNumberOfTimesCalled;
}


public virtual bool GoToFlowWasCalledWith(string id){
return (
id.Equals(GoToFlowParameter_id_LastCalledWith) );
}


        public void GoToFlow(string id)
        {
            _goToFlowNumberOfTimesCalled++;            

            GoToFlowParameter_id_LastCalledWith = id;
        }
}
}
