using Flowdock.Client.Domain;
using Flowdock.Navigation;
namespace MoqaLate.Autogenerated
{
public partial class NavigationManagerMoqaLate : INavigationManager
{


// -------------- GoToLobby ------------


        private int _goToLobbyNumberOfTimesCalled;        

        

        public virtual bool GoToLobbyWasCalled()
{
   return _goToLobbyNumberOfTimesCalled > 0;
}


public virtual bool GoToLobbyWasCalled(int times)
{
   return _goToLobbyNumberOfTimesCalled == times;
}


public virtual int GoToLobbyTimesCalled()
{
   return _goToLobbyNumberOfTimesCalled;
}




        public void GoToLobby()
        {
            _goToLobbyNumberOfTimesCalled++;            

            
        }


// -------------- GoToFlow ------------


        private int _goToFlowNumberOfTimesCalled;        

        public Flow GoToFlowParameter_flow_LastCalledWith;

        public virtual bool GoToFlowWasCalled()
{
   return _goToFlowNumberOfTimesCalled > 0;
}


public virtual bool GoToFlowWasCalled(int times)
{
   return _goToFlowNumberOfTimesCalled == times;
}


public virtual int GoToFlowTimesCalled()
{
   return _goToFlowNumberOfTimesCalled;
}


public virtual bool GoToFlowWasCalledWith(Flow flow){
return (
flow.Equals(GoToFlowParameter_flow_LastCalledWith) );
}


        public void GoToFlow(Flow flow)
        {
            _goToFlowNumberOfTimesCalled++;            

            GoToFlowParameter_flow_LastCalledWith = flow;
        }
}
}
