using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Flowdock.Services.Progress;
namespace MoqaLate.Autogenerated
{
public partial class ProgressService {MoqaLate : IProgressService {
{
// ------------ Property IsVisible
private bool _IsVisible;
public virtual bool IsVisible
{
get { return _IsVisible; }
}
public virtual void __SetIsVisible(bool val)
{
   _IsVisible = val;
}


// -------------- Show ------------


        private int _showNumberOfTimesCalled;        

        

        public virtual bool ShowWasCalled()
{
   return _showNumberOfTimesCalled > 0;
}


public virtual bool ShowWasCalled(int times)
{
   return _showNumberOfTimesCalled == times;
}


public virtual int ShowTimesCalled()
{
   return _showNumberOfTimesCalled;
}




        public void Show()
        {
            _showNumberOfTimesCalled++;            

            
        }


// -------------- Show ------------


        private int _showNumberOfTimesCalled;        

        public string ShowParameter_text_LastCalledWith;

        public virtual bool ShowWasCalled()
{
   return _showNumberOfTimesCalled > 0;
}


public virtual bool ShowWasCalled(int times)
{
   return _showNumberOfTimesCalled == times;
}


public virtual int ShowTimesCalled()
{
   return _showNumberOfTimesCalled;
}


public virtual bool ShowWasCalledWith(string text){
return (
text.Equals(ShowParameter_text_LastCalledWith) );
}


        public void Show(string text)
        {
            _showNumberOfTimesCalled++;            

            ShowParameter_text_LastCalledWith = text;
        }


// -------------- Hide ------------


        private int _hideNumberOfTimesCalled;        

        

        public virtual bool HideWasCalled()
{
   return _hideNumberOfTimesCalled > 0;
}


public virtual bool HideWasCalled(int times)
{
   return _hideNumberOfTimesCalled == times;
}


public virtual int HideTimesCalled()
{
   return _hideNumberOfTimesCalled;
}




        public void Hide()
        {
            _hideNumberOfTimesCalled++;            

            
        }
}
}
