using Flowdock.Client.Domain;
using System.Collections.Generic;
using Flowdock.MessageBoxes;
namespace MoqaLate.Autogenerated
{
public partial class MessageBoxServiceMoqaLate : IMessageBoxService
{


// -------------- ShowUsersMessageBox ------------


        private int _showUsersMessageBoxNumberOfTimesCalled;        

        public IEnumerable<User> ShowUsersMessageBoxParameter_users_LastCalledWith;

        public virtual bool ShowUsersMessageBoxWasCalled()
{
   return _showUsersMessageBoxNumberOfTimesCalled > 0;
}


public virtual bool ShowUsersMessageBoxWasCalled(int times)
{
   return _showUsersMessageBoxNumberOfTimesCalled == times;
}


public virtual int ShowUsersMessageBoxTimesCalled()
{
   return _showUsersMessageBoxNumberOfTimesCalled;
}


public virtual bool ShowUsersMessageBoxWasCalledWith(IEnumerable<User> users){
return (
users.Equals(ShowUsersMessageBoxParameter_users_LastCalledWith) );
}


        public void ShowUsersMessageBox(IEnumerable<User> users)
        {
            _showUsersMessageBoxNumberOfTimesCalled++;            

            ShowUsersMessageBoxParameter_users_LastCalledWith = users;
        }
}
}
