using Flowdock.Client.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Flowdock.Services.Navigation;
namespace MoqaLate.Autogenerated
{
public partial class NavigationManagerMoqaLate : INavigationManager
{


// -------------- GoToLobby ------------


        private int _goToLobbyNumberOfTimesCalled;        

        

        public virtual bool GoToLobbyWasCalled()
{
   return _goToLobbyNumberOfTimesCalled > 0;
}


public virtual bool GoToLobbyWasCalled(int times)
{
   return _goToLobbyNumberOfTimesCalled == times;
}


public virtual int GoToLobbyTimesCalled()
{
   return _goToLobbyNumberOfTimesCalled;
}




        public void GoToLobby()
        {
            _goToLobbyNumberOfTimesCalled++;            

            
        }


// -------------- GoToFlow ------------


        private int _goToFlowNumberOfTimesCalled;        

        public Flow GoToFlowParameter_flow_LastCalledWith;

        public virtual bool GoToFlowWasCalled()
{
   return _goToFlowNumberOfTimesCalled > 0;
}


public virtual bool GoToFlowWasCalled(int times)
{
   return _goToFlowNumberOfTimesCalled == times;
}


public virtual int GoToFlowTimesCalled()
{
   return _goToFlowNumberOfTimesCalled;
}


public virtual bool GoToFlowWasCalledWith(Flow flow){
return (
flow.Equals(GoToFlowParameter_flow_LastCalledWith) );
}


        public void GoToFlow(Flow flow)
        {
            _goToFlowNumberOfTimesCalled++;            

            GoToFlowParameter_flow_LastCalledWith = flow;
        }


// -------------- GoToUsers ------------


        private int _goToUsersNumberOfTimesCalled;        

        public string GoToUsersParameter_flowId_LastCalledWith;

        public virtual bool GoToUsersWasCalled()
{
   return _goToUsersNumberOfTimesCalled > 0;
}


public virtual bool GoToUsersWasCalled(int times)
{
   return _goToUsersNumberOfTimesCalled == times;
}


public virtual int GoToUsersTimesCalled()
{
   return _goToUsersNumberOfTimesCalled;
}


public virtual bool GoToUsersWasCalledWith(string flowId){
return (
flowId.Equals(GoToUsersParameter_flowId_LastCalledWith) );
}


        public void GoToUsers(string flowId)
        {
            _goToUsersNumberOfTimesCalled++;            

            GoToUsersParameter_flowId_LastCalledWith = flowId;
        }


// -------------- GoToMessageThread ------------


        private int _goToMessageThreadNumberOfTimesCalled;        

        public string GoToMessageThreadParameter_flowId_LastCalledWith;public int GoToMessageThreadParameter_threadId_LastCalledWith;

        public virtual bool GoToMessageThreadWasCalled()
{
   return _goToMessageThreadNumberOfTimesCalled > 0;
}


public virtual bool GoToMessageThreadWasCalled(int times)
{
   return _goToMessageThreadNumberOfTimesCalled == times;
}


public virtual int GoToMessageThreadTimesCalled()
{
   return _goToMessageThreadNumberOfTimesCalled;
}


public virtual bool GoToMessageThreadWasCalledWith(string flowId, int threadId){
return (
flowId.Equals(GoToMessageThreadParameter_flowId_LastCalledWith)  && 
threadId.Equals(GoToMessageThreadParameter_threadId_LastCalledWith) );
}


        public void GoToMessageThread(string flowId, int threadId)
        {
            _goToMessageThreadNumberOfTimesCalled++;            

            GoToMessageThreadParameter_flowId_LastCalledWith = flowId;GoToMessageThreadParameter_threadId_LastCalledWith = threadId;
        }
}
}
